"""Arduino-IDE sketch generation for the exported ESP32 Find-My beacon.

The generated ``tag.ino`` is the Arduino analog of the ESP-IDF export: it uses
the ESP32 Arduino core's raw ESP-IDF GAP API (exposed through the bundled
Bluetooth headers) to install the same OpenHaystack fragments:

* key[6:28] plus the key's top 2 bits go in the 31-byte advertising payload
  (single Apple manufacturer-data AD, no Flags AD, fits the legacy limit),
* key[0:6] are installed as the BLE random static address via
  ``esp_ble_gap_set_rand_addr()`` -- unlike MicroPython, the Arduino core can
  set the MAC, so the full key reassembles on Apple's server.

``string.Template`` (``$name`` placeholders) is used for substitution because
the C++ source is dense with ``{``/``}`` braces.
"""

from string import Template

from manager.esp_idf import _format_c_byte_array

_SKETCH_TEMPLATE = Template(r'''\
/* tag.ino - Find My offline beacon (Arduino-IDE, ESP32 Arduino core)
 *
 * Generated by the Find My manager on $generated
 * Device   : $device_name (account: $account_name)
 * Advertisement key (hex): $advertisement_key_hex
 *
 * Install in the Arduino IDE:
 *   Boards Manager -> install "esp32 by Espressif Systems",
 *   Tools -> Board -> pick your board (a plain ESP32 Dev Module with the
 *   default settings is fine), then Upload.
 *   If btStart() fails at boot, check the Tools -> Board selection, use a
 *   decent USB cable, or lower the Upload speed.
 *
 * A 28-byte key cannot fit inside the 31-byte legacy BLE advertisement, so
 * this uses the OpenHaystack fragmenting scheme (same as the ESP-IDF and
 * MicroPython exports, but complete):
 *   - advertising payload    : key[6:28] + key[0] >> 6 (+ Apple header),
 *   - BLE random static addr : key[0:6] via esp_ble_gap_set_rand_addr.
 * The Arduino core exposes the ESP-IDF GAP API, so the address can be
 * installed here and the tag is Find-My matchable (MicroPython cannot).
 * Since core 3.3.x the core frees the BLE controller/host memory during
 * initArduino() unless a sketch tells it BLE is in use; the
 * esp32-hal-alloc-ble-mem.h include below does that (required when calling
 * the ESP-IDF Bluetooth APIs directly, or btStart() fails on core 3.3.7).
 *
 * Battery: windowed advertising with an active-radio rest between cycles.
 * At a long BEACON_DELAY_S the average current is far below always-on; for
 * true coin-cell life move to a deep-sleep-capable ESP-IDF design.
 */

#include <Arduino.h>
#include <string.h>
#include "esp32-hal-bt.h"
#if __has_include("esp32-hal-alloc-ble-mem.h")
#include "esp32-hal-alloc-ble-mem.h"
#endif
#include "esp_bt_main.h"
#include "esp_gap_ble_api.h"

/* ---------------------- generated device settings ---------------------- */

/* The 28-byte advertisement key (P-224 public x-coordinate). */
static const uint8_t public_key[28] = {
$key_bytes
};

/* Advertising window per cycle (seconds). */
#define BEACON_WINDOW_S   $broadcast_sec
/* Idle time between cycles (seconds). */
#define BEACON_DELAY_S    $delay_sec

/* --------------------- beacon layout (OpenHaystack) -------------------- */

/* adv_data[31] = len(30) | 0xff | 0x4c 0x00 | 0x12 0x19 | status 0x00
 *                | key[6:28] (22 B) | key[0] >> 6 | hint 0x00            */
static uint8_t adv_data[31];

/* key[0:6] becomes the BLE random static address (bit 6..7 set => static,
 * bit 0 clear => not multicast). */
static esp_bd_addr_t rnd_addr;

static void set_payload_from_key(void)
{
    const uint8_t *key = public_key;
    adv_data[0] = 0x1E;                 /* advertising data length (30) */
    adv_data[1] = 0xFF;                 /* Manufacturer Specific Data */
    adv_data[2] = 0x4C;                 /* Apple Company ID (0x004C) */
    adv_data[3] = 0x00;
    adv_data[4] = 0x12;                 /* Find My offline type indicator */
    adv_data[5] = 0x19;
    adv_data[6] = 0x00;                 /* Apple Status Byte */
    memcpy(&adv_data[7], &key[6], 22);  /* key[6:28] */
    adv_data[29] = key[0] >> 6;         /* top 2 bits of the key */
    adv_data[30] = 0x00;                /* hint byte */
}

static void set_addr_from_key(void)
{
    memcpy(rnd_addr, public_key, 6);    /* key[0:6] */
    rnd_addr[0] |= 0xC0;                /* random static address marker */
}

static esp_ble_adv_params_t ble_adv_params = {
    .adv_int_min       = 0x140,         /* 200 ms (0x140 * 0.625 ms) */
    .adv_int_max       = 0x140,
    .adv_type          = ADV_TYPE_NONCONN_IND,
    .own_addr_type     = BLE_ADDR_TYPE_RANDOM,
    .channel_map       = ADV_CHNL_ALL,
    .adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
};

static void esp_gap_cb(esp_gap_ble_cb_event_t event, esp_ble_gap_cb_param_t *param)
{
    switch (event) {
    case ESP_GAP_BLE_ADV_DATA_RAW_SET_COMPLETE_EVT:
        if (param->adv_data_raw_cmpl.status == ESP_BT_STATUS_SUCCESS) {
            esp_ble_gap_start_advertising(&ble_adv_params);
        } else {
            Serial.printf("adv data set failed: %d\n", param->adv_data_raw_cmpl.status);
        }
        break;
    case ESP_GAP_BLE_ADV_START_COMPLETE_EVT:
        if (param->adv_start_cmpl.status != ESP_BT_STATUS_SUCCESS) {
            Serial.printf("adv start failed: %d\n", param->adv_start_cmpl.status);
        }
        break;
    default:
        break;
    }
}

static void beacon_cycle(void)
{
    set_payload_from_key();
    /* On completion the gap callback starts advertising. */
    esp_ble_gap_config_adv_data_raw(adv_data, sizeof(adv_data));
    delay(BEACON_WINDOW_S * 1000UL);
    esp_ble_gap_stop_advertising();
    delay((BEACON_DELAY_S - BEACON_WINDOW_S) * 1000UL);
}
static void ble_abort(const char *step)
{
    Serial.printf("%s failed (free heap %u bytes) - stuck here.\n",
                  step, ESP.getFreeHeap());
    Serial.println("Core 3.3.7 frees the BLE memory unless a sketch says");
    Serial.println("BLE is in use; the esp32-hal-alloc-ble-mem.h include in");
    Serial.println("this file fixes that. If it still fails, update the");
    Serial.println("esp32 core in Boards Manager (3.3.8 or newer).");
    while (true) { delay(1000); }
}

void setup()
{
    Serial.begin(115200);

    set_addr_from_key();
    Serial.printf("Find My beacon starting, addr "
                  "%02x:%02x:%02x:%02x:%02x:%02x\n",
                  rnd_addr[0], rnd_addr[1], rnd_addr[2],
                  rnd_addr[3], rnd_addr[4], rnd_addr[5]);

    /* btStart() initializes and enables the BLE controller the way the
     * Arduino core expects (the raw esp_bt_controller_* API is not exposed
     * to sketches). */
    if (!btStart()) { ble_abort("btStart"); }
    if (esp_bluedroid_init() != ESP_OK) { ble_abort("bluedroid init"); }
    if (esp_bluedroid_enable() != ESP_OK) { ble_abort("bluedroid enable"); }
    if (esp_ble_gap_register_callback(esp_gap_cb) != ESP_OK) { ble_abort("gap register"); }
    if (esp_ble_gap_set_rand_addr(rnd_addr) != ESP_OK) { ble_abort("set rand addr"); }

    Serial.printf("beacon loop: %d s window / %d s rest\n",
                  BEACON_WINDOW_S, BEACON_DELAY_S - BEACON_WINDOW_S);
}

void loop()
{
    beacon_cycle();
}
''')


def generate_sketch_ino(device, *, generated=None, broadcast_duration_sec=None, sleep_duration_min=None):
    """Build the Arduino ``tag.ino`` source for ``device`` as a str.

    ``broadcast_duration_sec`` / ``sleep_duration_min`` override the values
    stored on the device (used by the export form). The sketch keeps an
    active-radio rest between beacon windows rather than deep sleep, so the
    delay is in seconds.
    """
    from datetime import datetime
    if generated is None:
        generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    broadcast = (broadcast_duration_sec if broadcast_duration_sec is not None
                 else device.broadcast_duration_sec)
    sleep_min = (sleep_duration_min if sleep_duration_min is not None
                 else device.sleep_duration_min)
    delay_sec = max(sleep_min * 60, broadcast + 1)
    return _SKETCH_TEMPLATE.substitute(
        generated=generated,
        device_name=device.name,
        account_name=device.account.name,
        advertisement_key_hex=device.advertisement_key_hex or "unknown (no key)",
        broadcast_sec=broadcast,
        delay_sec=delay_sec,
        key_bytes=_format_c_byte_array(device.advertisement_key),
    )
