"""Native ESP-IDF firmware generation for the exported ESP32 Find-My beacon.

The generated ``main.c`` installs the device's 28-byte advertisement key the
way the Find My network expects (the OpenHaystack "esp32-airtag" scheme):

* key[6:28] plus the key's top 2 bits go in the 31-byte advertising payload
  (a single Apple manufacturer-data AD, no Flags AD, so the whole thing fits
  the legacy 31-byte BLE limit, unlike the broken-out 39-byte payload);
* key[0:6] are installed as the device's BLE random static address via
  ``esp_ble_gap_set_rand_addr`` -- unlike MicroPython, native ESP-IDF can set
  the MAC, so the full 28-byte key reassembles from address + payload on
  Apple's server and the tag is Find-My matchable.

``string.Template`` (``$name`` placeholders) is used for substitution because
the C source is dense with ``{``/``}`` braces.
"""

from string import Template

_FIRMWARE_TEMPLATE = Template('''\
/* main.c - Find My offline beacon (native ESP-IDF firmware)
 *
 * Generated by the Find My manager on $generated
 * Device   : $device_name (account: $account_name)
 * Advertisement key (hex): $advertisement_key_hex
 *
 * Build & flash with ESP-IDF (Bluedroid Bluetooth stack):
 *   idf.py set-target esp32s3        (or esp32 / your chip)
 *   idf.py build
 *   idf.py -p PORT flash monitor     # PORT e.g. /dev/cu.usbmodem1301
 *
 * A 28-byte key cannot fit inside the 31-byte legacy BLE advertisement, so
 * this uses the OpenHaystack fragmenting scheme (the same one as the
 * MicroPython export, but complete):
 *   - advertising payload    : key[6:28] + key[0] >> 6 (+ Apple header),
 *   - BLE random static addr : key[0:6] via esp_ble_gap_set_rand_addr.
 * Native ESP-IDF can install that address; MicroPython cannot, which is why
 * this firmware is Find-My matchable and the MicroPython build is not.
 *
 * Battery: windowed advertising with an active-radio rest between cycles.
 * At a long BEACON_DELAY_S the average current is far below always-on; for
 * true coin-cell life move to a timer-based deep-sleep design.
 */

#include <stdint.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_bt.h"
#include "esp_bt_main.h"
#include "esp_gap_ble_api.h"

#define LOG_TAG "findmy_tag"

/* ---------------------- generated device settings ---------------------- */

/* The 28-byte advertisement key (P-224 public x-coordinate). */
static const uint8_t public_key[28] = {
$key_bytes
};

/* Advertising window per cycle (seconds). */
#define BEACON_WINDOW_S   $broadcast_sec
/* Idle time between cycles (seconds). */
#define BEACON_DELAY_S    $delay_sec

/* --------------------- beacon layout (OpenHaystack) -------------------- */

/* adv_data[31] = len(30) | 0xff | 0x4c 0x00 | 0x12 0x19 | status 0x00
 *                | key[6:28] (22 B) | key[0] >> 6 | hint 0x00            */
static uint8_t adv_data[31];

/* key[0:6] becomes the BLE random static address (bit 6..7 set => static,
 * bit 0 clear => not multicast). */
static esp_bd_addr_t rnd_addr;

static void set_payload_from_key(void)
{
    const uint8_t *key = public_key;
    adv_data[0] = 0x1E;                 /* advertising data length (30) */
    adv_data[1] = 0xFF;                 /* Manufacturer Specific Data */
    adv_data[2] = 0x4C;                 /* Apple Company ID (0x004C) */
    adv_data[3] = 0x00;
    adv_data[4] = 0x12;                 /* Find My offline type indicator */
    adv_data[5] = 0x19;
    adv_data[6] = 0x00;                 /* Apple Status Byte */
    memcpy(&adv_data[7], &key[6], 22);  /* key[6:28] */
    adv_data[29] = key[0] >> 6;         /* top 2 bits of the key */
    adv_data[30] = 0x00;                /* hint byte */
}

static void set_addr_from_key(void)
{
    memcpy(rnd_addr, public_key, 6);    /* key[0:6] */
    rnd_addr[0] |= 0xC0;                /* random static address marker */
}

static esp_ble_adv_params_t ble_adv_params = {
    .adv_int_min       = 0x140,         /* 200 ms (0x140 * 0.625 ms) */
    .adv_int_max       = 0x140,
    .adv_type          = ADV_TYPE_NONCONN_IND,
    .own_addr_type     = BLE_ADDR_TYPE_RANDOM,
    .channel_map       = ADV_CHNL_ALL,
    .adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
};

static void esp_gap_cb(esp_gap_ble_cb_event_t event, esp_ble_gap_cb_param_t *param)
{
    switch (event) {
    case ESP_GAP_BLE_ADV_DATA_RAW_SET_COMPLETE_EVT:
        if (param->adv_data_raw_cmpl.status == ESP_BT_STATUS_SUCCESS) {
            esp_ble_gap_start_advertising(&ble_adv_params);
        } else {
            ESP_LOGE(LOG_TAG, "adv data set failed: %d",
                     param->adv_data_raw_cmpl.status);
        }
        break;
    case ESP_GAP_BLE_ADV_START_COMPLETE_EVT:
        if (param->adv_start_cmpl.status != ESP_BT_STATUS_SUCCESS) {
            ESP_LOGE(LOG_TAG, "adv start failed: %d",
                     param->adv_start_cmpl.status);
        }
        break;
    default:
        break;
    }
}

static void beacon_cycle(void)
{
    set_payload_from_key();
    /* On completion the gap callback starts advertising. */
    esp_ble_gap_config_adv_data_raw(adv_data, sizeof(adv_data));
    vTaskDelay(pdMS_TO_TICKS(BEACON_WINDOW_S * 1000));
    esp_ble_gap_stop_advertising();
    vTaskDelay(pdMS_TO_TICKS((BEACON_DELAY_S - BEACON_WINDOW_S) * 1000));
}

void app_main(void)
{
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }
    ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));

    esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_bt_controller_init(&bt_cfg));
    ESP_ERROR_CHECK(esp_bt_controller_enable(ESP_BT_MODE_BLE));

    ESP_ERROR_CHECK(esp_bluedroid_init());
    ESP_ERROR_CHECK(esp_bluedroid_enable());
    ESP_ERROR_CHECK(esp_ble_gap_register_callback(esp_gap_cb));

    set_addr_from_key();
    ESP_LOGI(LOG_TAG, "advertising as %02x:%02x:%02x:%02x:%02x:%02x",
             rnd_addr[0], rnd_addr[1], rnd_addr[2],
             rnd_addr[3], rnd_addr[4], rnd_addr[5]);
    ESP_ERROR_CHECK(esp_ble_gap_set_rand_addr(rnd_addr));

    ESP_LOGI(LOG_TAG, "beacon loop: %d s window / %d s rest",
             BEACON_WINDOW_S, BEACON_DELAY_S - BEACON_WINDOW_S);
    while (1) {
        beacon_cycle();
    }
}
''')


def _format_c_byte_array(key_bytes):
    """Format 28 bytes as an indented, comma-separated C array literal."""
    groups = []
    for start in range(0, len(key_bytes), 8):
        groups.append("    " + ", ".join("0x{:02x}".format(b) for b in key_bytes[start:start + 8]))
    return ",\n".join(groups)


def generate_firmware_c(device, *, generated=None, broadcast_duration_sec=None, sleep_duration_min=None):
    """Build the ESP-IDF ``main.c`` source for ``device`` as a str.

    ``broadcast_duration_sec`` / ``sleep_duration_min`` override the values
    stored on the device (used by the export form). The firmware keeps an
    active-radio rest between beacon windows rather than deep sleep, so the
    delay is in seconds.
    """
    from datetime import datetime
    if generated is None:
        generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    broadcast = (broadcast_duration_sec if broadcast_duration_sec is not None
                 else device.broadcast_duration_sec)
    sleep_min = (sleep_duration_min if sleep_duration_min is not None
                 else device.sleep_duration_min)
    delay_sec = max(sleep_min * 60, broadcast + 1)
    return _FIRMWARE_TEMPLATE.substitute(
        generated=generated,
        device_name=device.name,
        account_name=device.account.name,
        advertisement_key_hex=device.advertisement_key_hex or "unknown (no key)",
        broadcast_sec=broadcast,
        delay_sec=delay_sec,
        key_bytes=_format_c_byte_array(device.advertisement_key),
    )