"""MicroPython code generation for the exported ESP32 Find-My beacon.

The generated ``main.py`` follows the low-power routine from
``INSTRUCTIONS.md``: wake up, broadcast Apple's Find My offline beacon for a
short burst, then enter deep sleep. The 28-byte advertisement key is embedded
as a byte array.
"""

_MAIN_TEMPLATE = '''\
# main.py - Find My offline beacon for ESP32-S3 / ESP32 (MicroPython)
#
# Generated by the Find My manager on {generated}
# Device   : {device_name} (account: {account_name})
# Advertisement key (hex): {advertisement_key_hex}
#
# Battery-optimised: wakes up, broadcasts the Find My beacon for a short
# burst, then drops into deep sleep for a few minutes (~tens of uA).
#
# NOTE: A 28-byte Apple key cannot fit inside the 31-byte legacy BLE
# advertisement, so this uses the OpenHaystack fragmenting scheme: the
# last 22 bytes (plus the top 2 bits) are broadcast in the advertising
# payload, and the first 6 bytes must be installed as the device's BLE
# random static address. MicroPython cannot set the BLE MAC, so a fully
# working tag needs native ESP-IDF firmware (see README).

import bluetooth
import time
import machine


# Configuration parameters (tune per device in the manager)
BROADCAST_DURATION_SEC = {broadcast_duration_sec}   # seconds awake beaconing
SLEEP_DURATION_MIN = {sleep_duration_min}           # minutes in deep sleep


def generate_payload(public_key_bytes):
    if len(public_key_bytes) != 28:
        raise ValueError("The public key must be exactly 28 bytes.")

    payload = bytearray()
    payload.append(0x1E)                                # AD length (30)
    payload.append(0xFF)                                # Manufacturer Specific Data type
    payload.extend(b"\\x4c\\x00")                        # Apple Company ID (0x004C)
    payload.extend(b"\\x12\\x19")                        # Find My offline type indicator
    payload.append(0x00)                                # Apple Status Byte
    payload.extend(public_key_bytes[6:28])             # Public key tail (22 bytes)
    payload.append(public_key_bytes[0] >> 6)           # Top 2 bits of the key
    payload.append(0x00)                                # Hint byte
    return payload


def ble_address_from_key(public_key_bytes):
    # The Find My server reassembles the full 28-byte key from this address
    # (key[0..5]) plus the advertising payload (key[6..27] + top 2 bits).
    addr = bytearray(public_key_bytes[0:6])
    addr[0] |= 0b11000000                              # random static address marker
    return addr


# Paste the raw byte array derived from your key pair here
my_public_key = bytes([
{key_bytes}
])


# 1. Initialize BLE and begin broadcasting
ble = bluetooth.BLE()
ble.active(True)
adv_payload = generate_payload(my_public_key)
# Broadcast interval: 200ms (200000us) is optimal for Apple devices to capture it quickly
ble.gap_advertise(200000, adv_data=adv_payload, connectable=False)
print("Woke up. Broadcasting Find My beacon...")

# 2. Keep the beacon alive for the designated capture window
time.sleep(BROADCAST_DURATION_SEC)

# 3. Cleanly shut down Bluetooth radios before dropping into deep sleep
ble.gap_advertise(None)
ble.active(False)
print("Entering deep sleep for %d minutes..." % SLEEP_DURATION_MIN)

# 4. Configure deep sleep wakeup timer and sleep
#    Math ensures the conversion from minutes -> seconds -> milliseconds -> microseconds
sleep_time_ms = SLEEP_DURATION_MIN * 60 * 1000
machine.deepsleep(sleep_time_ms)
'''


def _format_key_bytes(key_bytes):
    """Format 28 bytes as an indented, comma-separated byte array literal."""
    groups = []
    for start in range(0, len(key_bytes), 8):
        groups.append("    " + ", ".join("0x{:02x}".format(b) for b in key_bytes[start:start + 8]))
    return ",\n".join(groups)


def generate_main_py(device, *, generated=None, broadcast_duration_sec=None, sleep_duration_min=None):
    """Build the ``main.py`` source for ``device`` as a str.

    ``broadcast_duration_sec`` / ``sleep_duration_min`` override the values
    stored on the device (used by the export form).
    """
    from datetime import datetime
    if generated is None:
        generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    return _MAIN_TEMPLATE.format(
        generated=generated,
        device_name=device.name,
        account_name=device.account.name,
        advertisement_key_hex=device.advertisement_key_hex or "unknown (no key)",
        broadcast_duration_sec=broadcast_duration_sec if broadcast_duration_sec is not None else device.broadcast_duration_sec,
        sleep_duration_min=sleep_duration_min if sleep_duration_min is not None else device.sleep_duration_min,
        key_bytes=_format_key_bytes(device.advertisement_key),
    )


def generate_boot_py():
    """Optional ``boot.py`` nothing is needed: keep it minimal and canonical."""
    return "# Generated by the Find My manager. Nothing to configure.\n"