"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _csv(name, default):
    """Split a comma-separated environment variable, or return *default*."""
    raw = os.environ.get(name)
    if raw is None:
        return list(default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def _flag(name, default=False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")

# Data directory for FindMy.py session state (auth, anisette libraries).
# e.g. BARE_DIR / ".findmy"
FINDMY_STATE_DIR = BASE_DIR / ".findmy"
# Optionally use a remote anisette server (e.g. your macless-haystack anisette)
# instead of the built-in provider, e.g. "http://anisette:6969".
FINDMY_ANISETTE_URL = ""


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-default-key-set-yours"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Public hostname(s) the reverse proxy serves. Do not leave "*" in production.
ALLOWED_HOSTS = _csv("ALLOWED_HOSTS", ["*"] if DEBUG else [])

# --------------------------------------------------------------------------
# HTTPS reverse proxy, CSRF, CORS
#
# Terminate TLS on nginx / Caddy / Traefik and forward
#   X-Forwarded-Proto: https
#   X-Forwarded-Host:  public.example
# so Django builds https:// URLs and accepts CSRF from the public origin.
# Set CSRF_TRUSTED_ORIGINS / CORS_ALLOWED_ORIGINS to that origin, e.g.
#   https://findmy.example.com
# --------------------------------------------------------------------------

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Proxy should redirect HTTP→HTTPS. Leave False here to avoid redirect loops
# if the forwarded proto header is missing. Set HTTPS=1 when cookies must be
# Secure (typical behind TLS).
_https = _flag("HTTPS", default=not DEBUG)
SECURE_SSL_REDIRECT = _flag("SECURE_SSL_REDIRECT", default=False)

CSRF_TRUSTED_ORIGINS = _csv(
    "CSRF_TRUSTED_ORIGINS",
    [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://127.0.0.1:8080",
        "http://localhost:8080",
    ],
)
CSRF_COOKIE_SECURE = _https
SESSION_COOKIE_SECURE = _https
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_NAME = "csrftoken"
CSRF_HEADER_NAME = "HTTP_X_CSRFTOKEN"

CORS_ALLOWED_ORIGINS = _csv("CORS_ALLOWED_ORIGINS", CSRF_TRUSTED_ORIGINS)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    "authorization",
    "x-csrftoken",
    "x-session-token",
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_q",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.mfa",
    "django_bootstrap5",
    "manager",
    "api",
]

SITE_ID = 1

BOOTSTRAP5 = {
    "checkbox_style": "switch",
}

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "api.auth.DrfBearerTokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.middleware.ManagerLoginRequiredMiddleware",
]

ROOT_URLCONF = "config.urls"

AUTHENTICATION_BACKENDS = [
    "allauth.account.auth_backends.AuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Browser UI session login (manager/urls.py). allauth itself stays headless
# (mobile/API-first); the manager UI logs in through Django's own LoginView.
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"


# django-q2 cluster using the built-in ORM broker (no Redis needed).
# Run `python manage.py qcluster` to process queued tasks.
Q_CLUSTER = {
    "name": "findmy-manager",
    "orm": "default",
    "workers": 2,
    "timeout": 600,
    "retry": 1200,
    "queue_limit": 100,
    "bulk": 5,
    "save_limit": 250,
    "label": "Find My manager",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --------------------------------------------------------------------------
# django-allauth (headless, mobile/API-first)
#
# The headless "app" client exposes a JSON authentication API under
# /api/app/v1/ (login, signup, logout, MFA, password reset, ...). A session
# token is issued during the auth flows; once authenticated, allauth mints a
# DRF auth token (see api/auth.py) that the mobile app sends as
# `Authorization: Bearer <token>` to the DRF resource endpoints.
# --------------------------------------------------------------------------

ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_PREVENT_ENUMERATION = False
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Find My manager] "

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "Find My manager <noreply@localhost>"

HEADLESS_ONLY = False
HEADLESS_SERVE_SPECIFICATION = True
HEADLESS_CLIENTS = ("app",)

# Token strategy: sessions for the auth flow, DRF Token as the access token.
HEADLESS_TOKEN_STRATEGY = "api.auth.DrfTokenStrategy"
