# Generated by Django 5.2.17 on 2026-09-07 23:44

import django.db.models.deletion
import manager.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppleAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A friendly label, e.g. 'Home'.", max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "password_encrypted",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Password"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_fetch_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When locations were last fetched for this account.",
                        null=True,
                    ),
                ),
                (
                    "last_fetch_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Status of the last fetch job, e.g. 'ok', 'needs_2fa', 'error'.",
                        max_length=32,
                    ),
                ),
                (
                    "last_fetch_message",
                    models.TextField(
                        blank=True, help_text="Detail message from the last fetch job."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Django user who owns this Apple account and its devices.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apple_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "advertisement_key_hex",
                    manager.models.EncryptedCharField(
                        blank=True,
                        help_text="28-byte P-224 advertisement (public) key as hex, e.g. from macless-haystack generate_keys.py.",
                        max_length=400,
                    ),
                ),
                (
                    "private_key_hex",
                    manager.models.EncryptedCharField(
                        blank=True,
                        help_text="28-byte P-224 private key as hex. Never expose this to the device itself; only the macless-haystack container needs it.",
                        max_length=400,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "broadcast_duration_sec",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Seconds the ESP32 stays awake beaconing after each wake-up.",
                    ),
                ),
                (
                    "sleep_duration_min",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Minutes the ESP32 spends in deep sleep between beacons.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Apple account whose macless-haystack container will decrypt this tag.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devices",
                        to="manager.appleaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, help_text="When the report was recorded."
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "horizontal_accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="Horizontal accuracy in meters.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="Apple status byte (bits 6-7 carry battery level).",
                    ),
                ),
                (
                    "confidence",
                    models.IntegerField(
                        blank=True, help_text="Location confidence 1-3.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="manager.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="appleaccount",
            constraint=models.UniqueConstraint(
                fields=("user", "email"), name="uniq_apple_account_email_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("account", "name"), name="uniq_device_per_account"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicelocation",
            constraint=models.UniqueConstraint(
                fields=("device", "timestamp"),
                name="uniq_location_per_device_timestamp",
            ),
        ),
    ]
